import pygame

WIDTH = 1000
HEIGHT = 1000

BLOCKSIZE = 10

DEPTH = 1
VISCOSITY = 1
PARTICLESPERCLICK = 10000

WIDTHBLOCKS = WIDTH//BLOCKSIZE
HEIGHTBLOCKS = HEIGHT//BLOCKSIZE

FONT = pygame.font.SysFont("Arial", 18)